filme/urls.py
# url - view - template

from django.urls import path, reverse_lazy
from .views import Homefilmes, Homepage, DetalhesFilme, PesquisaFilme, PaginaPerfil, CriarConta
from django.contrib.auth import views as auth_view
# fazer essa importacao

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', DetalhesFilme.as_view(), name='detalhesfilme'),
    path('pesquisa/',PesquisaFilme.as_view(),name='pesquisafilme'),
    path('login',auth_view.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout',auth_view.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('editarPerfil/<int:pk>',PaginaPerfil.as_view(),name='editarPerfil'),
    path('criarConta',CriarConta.as_view(),name='criarConta'),
    path('mudarSenha/', auth_view.PasswordChangeView.as_view(template_name='editarPerfil.html',
                                                             success_url=reverse_lazy('filme:homefilmes')),name='mudarSenha'),
    
]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
# fazer essa importacao

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme'))
]
# configurar essas variaveis

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

#Kind of filmes
LISTA_CATEGORIAS = (
    ("ANALISES", "Analises"),
    ("PROGRAMACAO", "Programacao"),
    ("APRESENTACAO", "Apresentacao"),
    ("OUTROS", "Outros,")
)

# criar filmes


class Filme(models.Model):

    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    # criando essa funcao para a descricao aparecer amigavelmente

    def __str__(self):

        return self.titulo

# criar os episodios


class Episodio(models.Model):
    filme = models.ForeignKey(
        'filme', related_name='episodios', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):

        return self.filme.titulo + " - " + self.titulo
    
class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField('Filme')

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from.models import Usuario
from django import forms 

class FormHomePage(forms.Form): #Usa o formulario padrao do django
    
    email = forms.EmailField(label=False)

#necessario para criar o formulario personalizado
class CriarContaForm(UserCreationForm):
    
    email = forms.EmailField()
    
    # o nome desses campos são obrigatórios para a criação do formulário do usuario
    class Meta:
        model = Usuario
        fields =('username','email', 'password1','password2') 

filme/views.py
from typing import Any
from django.http import HttpResponse
from django.shortcuts import render , redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView ,FormView, UpdateView
from .forms import CriarContaForm, FormHomePage

from .models import Filme , Usuario
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class Homepage(FormView):
    
    template_name = "homepage.html"
    form_class= FormHomePage
    
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
          return redirect('filme:homefilmes')       #redireciona para home filmes
        else:        
            return super().get(self, request, *args, **kwargs)   
        
        
    def get_success_url(self):
        
        email= self.request.POST.get('email')
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('filme:criarConta')
    
# sempre tem que criar url -view -html


class Homefilmes(LoginRequiredMixin,ListView):
    template_name = "homefilmes.html"
    # object list não uma lista já tem tudo pronto no ListView
    model = Filme  # lista de items do modelo


class DetalhesFilme(LoginRequiredMixin,DetailView):
    template_name = "detalhesfilme.html"
    model = Filme  # lista do nosso modelo

    def get(self, request, *args, **kwargs):

        # precisa descobrir que filme o usuario está acessando
        # somar um às visualizações do filme
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        
        # redireciona o usuário para o link final
        return super().get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetalhesFilme, self).get_context_data(**kwargs)
        # filtrar a tabela de filmes e pegar os filmes cuja categoria seja programacao (object)
        # self.get_object()
        filmes_relacionados = Filme.objects.filter(
            categoria=self.get_object().categoria)  # [0:5] limita a no máximo trazer 5 filmes
        context['filmes_relacionados'] = filmes_relacionados
        return context
    
class PesquisaFilme(LoginRequiredMixin,ListView):
    template_name = "pesquisa.html"
    model = Filme  # lista do nosso modelo
    
    
    #object_list faz o filtro da caixa de pesquisa
    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = Filme.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            
            return None
        


class PaginaPerfil(LoginRequiredMixin,UpdateView):
        
    template_name = "editarPerfil.html"
    model = Usuario
    fields = ['first_name','last_name','email']
    
    def get_success_url(self):
        return reverse('filme:homefilmes')
    
    
    
class CriarConta(FormView):
        
    template_name = "criarConta.html"  
    
    form_class = CriarContaForm  
    
    def form_valid(self, form):
        form.save()  #aqui que efetivamente cria o usuário no banco
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('filme:login') #usa reverse quando espera um texto de um link  pois o redirect não funciona
    
    
# Fazendo com function
# def homepage(request):
#    return render(request, "homepage.html")

# fazendo com function
# def homefilmes(request):
#    context = {}
#    lista_filmes = Filme.objects.all()
#    context['lista_filmes'] = lista_filmes
#    return render(request, "homefilmes.html", context)

filme/templates/criarConta.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}
 Create Account 
 {% endblock %}
{% block content %}
<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
   <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
       <form method="post">
         {% csrf_token%}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Create an account to continue</legend>
               {{form |crispy }}
           </fieldset>
           <button class="bg-red-600 text-white w-full md:text-lg rounded-md" type="submit">Create an account</button>
       </form>

   </div>
</header>

<footer class=" px-5 py-10 ">
   <ul class="flex justify-between items-center">
       
       <li>&copy; 2023</li>
       <li> Made in Python (Django)</li>
       <li>By Alex</li>
   </ul>
</footer>

{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %} {% block titulo %} HomeFilmes AlexFlix {% endblock %}
{%block content %}

<main class="bg-primary_black min-h-screen w-full">
  <section
    class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover"
    style="background-image: url('{{filme.thumb.url}}')"
  >
    <div>
      <h2 class="text-6xl font-semibold text-white my-4">{{object.titulo}}</h2>
      <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
        {{object.descricao|slice:":100"}}...
      </p>
      <div class="flex my-4">
        <a href="{{object.episodios.first.video}}">
          <button
            class="flex items-center bg-white py-2 px-5 rounded-md"
            style="color: black"
          >
            <ion-icon name="play" class="text-2xl"></ion-icon>
            <span class="ml-3 font-medium"> Play </span>
          </button>
        </a>
      </div>
    </div>
  </section>
  <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-3xl font-medium">{{object.descricao}}</h2>
      <div class="flex justify-left items-center min-w-full movie_lis">
        <p class="text-gray-100 text-lg">
          Views: {{object.visualizacoes}}
        </p>
      </div>

      <div style="margin-top: 2rem; margin-bottom: 2rem">
        <h2 class="text-gray-200 text-3xl font-medium">Episodes</h2>
        <h3 class="text-lg">
          {%for episodio in object.episodios.all %}
          <a href="{{episodio.video}}"
            ><p>Episodes {{forloop.counter}}: {{episodio.titulo}}</p></a
          >
          {% endfor %}
        </h3>
      </div>
    </div>
  </section>

  <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Related</h2>
  
     
      <div class="flex flex-wrap items-center min-w-full movie_lis">
        {% for filme in filmes_relacionados %}
        <div
          class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96"
        >
        <a href="{% url 'filme:detalhesfilme' filme.pk %}">{{filme.titulo}}</a>
            <img
              src="{{filme.thumb.url}}"
              class="object-cover w-full h-full"
              alt=""
            />
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</main>

{% endblock %}

filme/templates/editarPerfil.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}
 Edit Profile
 {% endblock %}
{% block content %}
  

<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
   <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
       <h2 class="text-2xl">{{user.email}}</h2>

       <form method="post">
         {% csrf_token %}
           <fieldset class="form-group">
               {{form | crispy }}

               <legend class="border-bottom mb-4">Edit the fields below to edit your profile</legend>

           </fieldset>
           <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Edit Profile</button>
       </form>
       <small><a href="{% url 'filme:mudarSenha'%}">Do you want to change your password?</a></small>
   </div>
</header>

<footer class=" px-5 py-10 ">
   <ul class="flex justify-between items-center">
       
       <li>&copy; 2023</li>
       <li> Made in Python (Django)</li>
       <li>By Alex</li>
   </ul>
</footer>

{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %} {% block titulo %} HomeFilmes Hashflix {% endblock %}
{% block head %}
    <style> 

    </style>
{% endblock %}
{%block content %}

{% load static %}
<main class='bg-primary_black min-h-screen w-full'>
  <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{filme_destaque.thumb.url}}');">
      <div>
          <h2 class="text-6xl font-semibold text-white my-4">
                 {{ filme_destaque.titulo }}
          </h2>
          <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
            {{ filme_destaque.descricao }}
          </p>
          <div class="flex my-4">
              <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                  <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                      <ion-icon name="play" class="text-2xl"></ion-icon>
                      <span class="ml-3 font-medium " >
                          Play
                      </span>
                  </button>
              </a>
          </div>
      </div>
  </section> 

  <section class='bg-primary_black flex justify-center py-10'>
    <div class="p-8 w-10/12 relative" >
        <h2 class="text-gray-200 text-2xl font-medium">
            New
        </h2>
        <div class="wrapper">
          <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
            <a href="#section2" class="arrow__btn text-6xl page">‹</a>
            {% for filme in lista_filmes_recentes %}
            {% if forloop.counter < 5  %}  
              <div class="item h-64 w-1/4 m-4">
                  <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                    <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                  </a>
              </div>
              {% endif %}
              {% endfor %}
                <a href="#section2" class="arrow__btn text-6xl">›</a>
          </section>
            {% if lista_filmes_recentes|length > 4%}
              <section id="section2" class="flex flex-nowrap items-center justify-center">
                <a href="#section1" class="arrow__btn text-6xl">‹</a>
                  {% for filme in lista_filmes_recentes %}
                  {% if forloop.counter > 4 %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="#">
                        <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                  {% endif %}
                  {% endfor %}
                <a href="#section1" class="arrow__btn text-6xl">›</a>
              </section>
              {% endif %}
            <h2 class="text-gray-200 text-2xl font-medium">
                Em Alta
               </h2>
            <div class="wrapper">
                
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                {% for filme in lista_filmes_em_alta %}
                {% if forloop.counter < 5  %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="#">
                        <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                    {% endif %}
                     {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
              
              {% if lista_filmes_em_alta|length > 4%}
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                    {% for filme in lista_filmes_em_alta %}
                        {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="#">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                    {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>  
                {% endif %}
        </div>
    </div>


    <div class="p-8 w-10/12 relative" >
          <h2 class="text-gray-200 text-2xl font-medium">
            Continue watching
             </h2>
          <div class="wrapper">
              
            <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
              <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
              {% for filme in request.user.filmes_vistos.all %}
              {% if forloop.counter < 5  %}
                <div class="item h-64 w-1/4 m-4">
                    <a href="#">
                      <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                    </a>
                </div>
                  {% endif %}
                   {% endfor %}
                  <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
            </section>
            
            {% if request.user.filmes_vistos.all|length > 4%}
                <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                  <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                  {% for filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter > 4 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="#">
                          <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                    {% endif %}
                  {% endfor %}
                  <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                </section>  
              {% endif %}
      </div>
  </div>
</section>


</main>

{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %} {% block titulo %} HomePage Hashflix {% endblock %}
{%block content %}

{% block head %} 
<style>
    #id_email{
        width:100%;
        color: #000000;
        padding: 5px 5px;
    }
</style>
{% endblock %}

{% load static %}

<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
  <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

      <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
        AlexFlix movies and series, all in one place.
      </h1>
      <h3 class="text-xl md:text-xl py-5">
        Watch wherever you want. Cancel whenever you want.
      </h3>
      <h4 class="text-sm md:text-lg pb-3">
        Want to get started? Enter your email below to access.
      </h4>

      <div class="w-full flex justify-center">
          <div class="flex justify-center items-center w-11/12 md:w-10/12">
              <form method="post" class="w-6/12 justify-center">
                  {% csrf_token%}
                  <div class="flex flex-grow items-stretch">
                      {{form}}
                  <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                      <span>
                          Access
                      </span>
                         <!-- biblioteca https://ionic.io/ionicons/usage-->
                         <ion-icon name="chevron-forward-outline" class="text-2xl md hydrated" role="img" aria-label="chevron forward outline"></ion-icon>
                  </button>

                  </div>
              </form>
              </a>
          </div>
      </div>

  </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
  <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
      <h2 class="md:text-5xl text-4xl font-semibold mb-4">
          Enjoy on your TV.
      </h2>
      <h5 class="md:text-xl text-lg">
          Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
      </h5>
  </div>
  <div class='md:w-1/2 flex justify-center items-center'>
      {% load static %}
      <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
  </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
  <div class='md:w-1/2 flex justify-center items-center '>
    {% load static %}
      <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
  </div>

  <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
      <h2 class="md:text-5xl text-4xl font-semibold mb-4">
          Download your shows to watch offline.
      </h2>
      <h5 class="md:text-xl text-lg">
          Save your favorites easily and always have something to watch.
      </h5>
  </div>
  
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
  <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
      <h2 class="md:text-5xl text-4xl font-semibold mb-4">
          Create profiles for kids.
      </h2>
      <h5 class="md:text-xl text-lg">
          Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
      </h5>
  </div>
  <div class='md:w-1/2 flex justify-center items-center'>
      {% load static %}
      <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
  </div>
</section>
<footer class=" px-5 py-10 ">
  <ul class="flex justify-between items-center">
      
      <li>&copy; 2023</li>
      <li> Made in Python (Django)</li>
      <li>By Alex</li>
  </ul>
</footer>
{% endblock %}

filme/templates/login.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}
 HomePage AlexFlix 
 {% endblock %}
{% block content %}
<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
   <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
       <form method="post">
         {% csrf_token %} 
         
           <fieldset class="form-group">
               {{ form|crispy }} <!--usar o crisp forma que permite o usar o djanco com bootstrap pip install django-crispy-forms e pip install crispy-bootstrap5-->
               <legend class="border-bottom mb-4">Log in to continue</legend>
           </fieldset>
           <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Login</button>
       </form>
       <small>
        Do not have an account yet? <p><a href="{%url 'filme:criarConta'%}">Click here to create an account</a></p>
       </small>
   </div>
</header>

<footer class=" px-5 py-10 ">
   <ul class="flex justify-between items-center">
       
       <li>&copy; 2023</li>
       <li> Made in Python (Django)</li>
       <li>By Alex</li>
   </ul>
</footer>

{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %} 
{% load static %}
{% block titulo %}
 HomePage AlexFlix 
 {% endblock %}
{%block content %}


<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">You have logged out of your account</h2>
        <div class="flex flex-nowrap justify-center space-x-5 p-5">
        <a href="{% url 'filme:login' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Login</button></a>
        <a href="{% url 'filme:criarConta' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Create an account</button></a>
        </div>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Made in Python (Django)</li>
        <li>By Alex</li>
    </ul>
</footer>

{% endblock %}

filme/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Movie Search
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                  Search Results
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for filme in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titulo %} {% endblock %}</title>
    <!--Adiciona o tailwindcss e o bootstrap-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %} {% endblock %}
  </head>
  <body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %} {% block content %} {% endblock %}
    <!-- biblioteca https://ionic.io/ionicons/usage-->

    <script>
      const nav = document.querySelector('nav')

      document.addEventListener("scroll",e=>{
          if(scrollY>100){
              if(scrollY>window.innerHeight){
              nav.classList.add('invisible')
          }else{
              nav.classList.add('bg-gray-900')
              nav.classList.remove('invisible')
          }
          }else{
              nav.classList.remove('bg-gray-900')
              nav.classList.remove('invisible')
          }
      })
  </script>

    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
  </body>
</html>

templates/navbar.html
<!-- largura 100% do tawilwind-->
<nav class="w-full flex justifi-between items-center py-3 px-4 fixed z-50">
  <!--O tailwind divide e 12 pedaços no caso metade para o 1 div e metade para o segundo div-->

  <div class="w-6/12">
    <a href="/">
      {% load static %}
      <img
        class="w-2/12"
        src="{% static 'images/AlexFlix.png' %}"
        alt="Imagem quebrada"
      />
    </a>
  </div>
  
  <div class="w-6/12 flex flex-nowrap justify-end">
   
    {% if user.is_authenticated %}
    <div class="mr-2">
        <form method="get" action="{% url 'filme:pesquisafilme'%}">
        <input
          type="text" name="query" value="{{request.GET.query}}"
          class="py-1 px-2 rounded-md text-black"
          placeholder="Search.."
        />
        <input type="submit" value=""  />
      </form>
    </div>
      {% endif %}

    <div class="mr-2">
      {% if user.is_authenticated %}
      <a href="{% url 'filme:logout'%}">
        <button class="bg-red-600 text-whit py-1 px-3 rounded-md">Exit</button>
      </a>
       {%else%}
      <a href="{% url 'filme:login'%}">
        <button class="bg-red-600 text-whit py-1 px-3 rounded-md">Login</button>
      </a>
      {% endif %}
    </div>

    {% if user.is_authenticated %}
    <div class="mr-2">
      <a href="{% url 'filme:editarPerfil' user.pk %}">
        <button class="bg-red-600 text-whit py-1 px-3 rounded-md">
          Edit Profile
        </button>
      </a>
    </div>
    {% endif %}
  </div>
</nav>